DROP TABLE IF EXISTS `jiudu_access`;
CREATE TABLE `jiudu_access` (
  `role_id` smallint(6) unsigned NOT NULL,
  `g` varchar(30) NOT NULL,
  `m` varchar(30) NOT NULL,
  `a` varchar(30) NOT NULL,
  `node_id` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  KEY `role_id` (`role_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `jiudu_access` (`role_id`, `g`, `m`, `a`, `node_id`, `status`) VALUES
(3, 'Content', 'Archives', 'index', 96, 1),
(3, 'Content', 'Archives', 'add', 97, 1),
(3, 'Content', 'Archives', 'update', 98, 1),
(3, 'Content', 'Archives', 'foreverdelete', 99, 1),
(3, 'Content', 'Archives', 'caozuo', 100, 1),
(3, 'Content', 'Archives', 'updateflag', 101, 1),
(3, 'Content', 'Archives', 'move', 102, 1),
(3, 'Content', 'Archives', 'forbid', 103, 1),
(3, 'Content', 'Archives', 'resume', 104, 1),
(3, 'Content', 'Arctype', 'index', 105, 1),
(3, 'Content', 'Arctype', 'add', 106, 1),
(3, 'Content', 'Arctype', 'update', 107, 1),
(3, 'Content', 'Arctype', 'foreverdelete', 108, 1),
(3, 'Content', 'Arctype', 'move', 109, 1),
(3, 'Content', 'TopicType', 'index', 110, 1),
(3, 'Content', 'TopicType', 'add', 111, 1),
(3, 'Content', 'TopicType', 'update', 112, 1),
(3, 'Content', 'TopicType', 'foreverdelete', 113, 1),
(3, 'Content', 'Topic', 'index', 114, 1),
(3, 'Content', 'Topic', 'add', 115, 1),
(3, 'Content', 'Topic', 'update', 116, 1),
(3, 'Content', 'Topic', 'foreverdelete', 117, 1),
(3, 'Content', 'Keywords', 'index', 120, 1),
(3, 'Content', 'Keywords', 'add', 121, 1),
(3, 'Content', 'Keywords', 'update', 122, 1),
(3, 'Content', 'Keywords', 'foreverdelete', 123, 1),
(3, 'Content', 'Keywords', 'forbid', 124, 1),
(3, 'Content', 'Keywords', 'resume', 125, 1),
(3, 'Content', 'Searchkey', 'index', 126, 1),
(3, 'Edition', 'Templets', 'index', 128, 1),
(3, 'Edition', 'Edition', 'index', 132, 1),
(3, 'Edition', 'EditionRule', 'index', 139, 1),
(3, 'Edition', 'Zntiao', 'index', 146, 1),
(3, 'Edition', 'Zntiao', 'add', 147, 1),
(3, 'Edition', 'Zntiao', 'update', 148, 1),
(3, 'Edition', 'Zntiao', 'foreverdelete', 149, 1),
(3, 'Edition', 'Zntiao', 'forbid', 150, 1),
(3, 'Edition', 'Zntiao', 'resume', 151, 1),
(3, 'Model', 'Diyforms', 'index', 164, 1),
(3, 'Model', 'Diyforms', 'add', 165, 1),
(3, 'Model', 'Formfield', 'index', 170, 1),
(3, 'Model', 'Formfield', 'add', 171, 1),
(3, 'Model', 'Formfield', 'update', 172, 1),
(3, 'Model', 'Formfield', 'foreverdelete', 173, 1),
(3, 'Model', 'Formdata', 'index', 176, 1),
(3, 'Model', 'Formdata', 'foreverdelete', 179, 1),
(3, 'Model', 'Formdata', 'forbid', 180, 1),
(3, 'Model', 'Formdata', 'resume', 181, 1),
(3, 'Ad', 'Ad', 'index', 188, 1),
(3, 'Ad', 'Ad', 'add', 189, 1),
(3, 'Ad', 'Ad', 'update', 190, 1),
(3, 'Ad', 'Ad', 'foreverdelete', 191, 1),
(3, 'Ad', 'Ad', 'preview', 192, 1),
(3, 'Ad', 'Ad', 'make', 193, 1),
(2, 'Admin', 'User', 'index', 35, 1),
(2, 'Admin', 'User', 'add', 36, 1),
(2, 'Admin', 'User', 'uodate', 37, 1),
(2, 'Admin', 'User', 'foreverdelete', 38, 1),
(2, 'Admin', 'User', 'password', 39, 1),
(2, 'Admin', 'User', 'forbid', 40, 1),
(2, 'Admin', 'User', 'resume', 41, 1),
(2, 'Admin', 'User', 'tongji', 42, 1),
(2, 'Admin', 'Role', 'index', 43, 1),
(2, 'Admin', 'Role', 'add', 44, 1),
(2, 'Admin', 'Role', 'update', 45, 1),
(2, 'Admin', 'Role', 'foreverdelete', 46, 1),
(2, 'Admin', 'Role', 'privilege', 47, 1),
(2, 'Admin', 'Role', 'forbid', 48, 1),
(2, 'Admin', 'Role', 'resume', 49, 1),
(2, 'Admin', 'Sysconfig', 'index', 50, 1),
(2, 'Admin', 'Sysconfig', 'add', 51, 1),
(2, 'Admin', 'Sysconfig', 'update', 52, 1),
(2, 'Admin', 'Sysconfig', 'foreverdelete', 53, 1),
(2, 'Admin', 'Sysconfig', 'watermark', 54, 1),
(2, 'Admin', 'Sysconfig', 'soft', 55, 1),
(2, 'Admin', 'Module', 'index', 56, 1),
(2, 'Admin', 'Module', 'add', 57, 1),
(2, 'Admin', 'Module', 'foreverdelete', 58, 1),
(2, 'Admin', 'Module', 'install', 59, 1),
(2, 'Admin', 'Module', 'uninstall', 60, 1),
(2, 'Admin', 'Module', 'info', 61, 1),
(2, 'Admin', 'Makehtml', 'index', 62, 1),
(2, 'Admin', 'Makehtml', 'home', 63, 1),
(2, 'Admin', 'Makehtml', 'arctype', 64, 1),
(2, 'Admin', 'Makehtml', 'archives', 65, 1),
(2, 'Admin', 'Makehtml', 'topic', 66, 1),
(2, 'Admin', 'Makehtml', 'ad', 67, 1),
(2, 'Admin', 'Loginlog', 'index', 88, 1),
(2, 'Admin', 'Loginlog', 'foreverdelete', 89, 1),
(2, 'Admin', 'Loginlog', 'deleteall', 90, 1),
(2, 'Admin', 'Loginlog', 'emptydata', 91, 1),
(2, 'Admin', 'Syslog', 'index', 92, 1),
(2, 'Admin', 'Syslog', 'foreverdelete', 93, 1),
(2, 'Admin', 'Syslog', 'deleteall', 94, 1),
(2, 'Admin', 'Syslog', 'emptydata', 95, 1),
(2, 'Content', 'Archives', 'index', 96, 1),
(2, 'Content', 'Archives', 'add', 97, 1),
(2, 'Content', 'Archives', 'update', 98, 1),
(2, 'Content', 'Archives', 'foreverdelete', 99, 1),
(2, 'Content', 'Archives', 'caozuo', 100, 1),
(2, 'Content', 'Archives', 'updateflag', 101, 1),
(2, 'Content', 'Archives', 'move', 102, 1),
(2, 'Content', 'Archives', 'forbid', 103, 1),
(2, 'Content', 'Archives', 'resume', 104, 1),
(2, 'Content', 'Arctype', 'index', 105, 1),
(2, 'Content', 'Arctype', 'add', 106, 1),
(2, 'Content', 'Arctype', 'update', 107, 1),
(2, 'Content', 'Arctype', 'foreverdelete', 108, 1),
(2, 'Content', 'Arctype', 'move', 109, 1),
(2, 'Content', 'TopicType', 'index', 110, 1),
(2, 'Content', 'TopicType', 'add', 111, 1),
(2, 'Content', 'TopicType', 'update', 112, 1),
(2, 'Content', 'TopicType', 'foreverdelete', 113, 1),
(2, 'Content', 'Topic', 'index', 114, 1),
(2, 'Content', 'Topic', 'add', 115, 1),
(2, 'Content', 'Topic', 'update', 116, 1),
(2, 'Content', 'Topic', 'foreverdelete', 117, 1),
(2, 'Content', 'Keywords', 'index', 120, 1),
(2, 'Content', 'Keywords', 'add', 121, 1),
(2, 'Content', 'Keywords', 'update', 122, 1),
(2, 'Content', 'Keywords', 'foreverdelete', 123, 1),
(2, 'Content', 'Keywords', 'forbid', 124, 1),
(2, 'Content', 'Keywords', 'resume', 125, 1),
(2, 'Content', 'Searchkey', 'index', 126, 1),
(2, 'Content', 'Searchkey', 'foreverdelete', 127, 1),
(2, 'Edition', 'Templets', 'index', 128, 1),
(2, 'Edition', 'Templets', 'add', 129, 1),
(2, 'Edition', 'Templets', 'update', 130, 1),
(2, 'Edition', 'Templets', 'foreverdelete', 131, 1),
(2, 'Edition', 'Edition', 'index', 132, 1),
(2, 'Edition', 'Edition', 'add', 133, 1),
(2, 'Edition', 'Edition', 'update', 134, 1),
(2, 'Edition', 'Edition', 'foreverdelete', 135, 1),
(2, 'Edition', 'Edition', 'setdefault', 136, 1),
(2, 'Edition', 'Edition', 'forbid', 137, 1),
(2, 'Edition', 'Edition', 'resume', 138, 1),
(2, 'Edition', 'EditionRule', 'index', 139, 1),
(2, 'Edition', 'EditionRule', 'add', 140, 1),
(2, 'Edition', 'EditionRule', 'update', 141, 1),
(2, 'Edition', 'EditionRule', 'foreverdelete', 142, 1),
(2, 'Edition', 'EditionRule', 'sortrank', 143, 1),
(2, 'Edition', 'EditionRule', 'forbid', 144, 1),
(2, 'Edition', 'EditionRule', 'resume', 145, 1),
(2, 'Edition', 'Zntiao', 'index', 146, 1),
(2, 'Edition', 'Zntiao', 'add', 147, 1),
(2, 'Edition', 'Zntiao', 'update', 148, 1),
(2, 'Edition', 'Zntiao', 'foreverdelete', 149, 1),
(2, 'Edition', 'Zntiao', 'forbid', 150, 1),
(2, 'Edition', 'Zntiao', 'resume', 151, 1),
(2, 'Model', 'Conmodel', 'index', 152, 1),
(2, 'Model', 'Conmodel', 'add', 153, 1),
(2, 'Model', 'Conmodel', 'update', 154, 1),
(2, 'Model', 'Conmodel', 'foreverdelete', 155, 1),
(2, 'Model', 'Field', 'index', 158, 1),
(2, 'Model', 'Field', 'add', 159, 1),
(2, 'Model', 'Field', 'update', 160, 1),
(2, 'Model', 'Field', 'foreverdelete', 161, 1),
(2, 'Model', 'Diyforms', 'index', 164, 1),
(2, 'Model', 'Diyforms', 'add', 165, 1),
(2, 'Model', 'Diyforms', 'update', 166, 1),
(2, 'Model', 'Diyforms', 'foreverdelete', 167, 1),
(2, 'Model', 'Diyforms', 'forbid', 168, 1),
(2, 'Model', 'Diyforms', 'resume', 169, 1),
(2, 'Model', 'Formfield', 'index', 170, 1),
(2, 'Model', 'Formfield', 'add', 171, 1),
(2, 'Model', 'Formfield', 'update', 172, 1),
(2, 'Model', 'Formfield', 'foreverdelete', 173, 1),
(2, 'Model', 'Formdata', 'index', 176, 1),
(2, 'Model', 'Formdata', 'foreverdelete', 179, 1),
(2, 'Model', 'Formdata', 'forbid', 180, 1),
(2, 'Model', 'Formdata', 'resume', 181, 1),
(2, 'Ad', 'AdType', 'index', 184, 1),
(2, 'Ad', 'AdType', 'add', 185, 1),
(2, 'Ad', 'AdType', 'update', 186, 1),
(2, 'Ad', 'AdType', 'foreverdelete', 187, 1),
(2, 'Ad', 'Ad', 'index', 188, 1),
(2, 'Ad', 'Ad', 'add', 189, 1),
(2, 'Ad', 'Ad', 'update', 190, 1),
(2, 'Ad', 'Ad', 'foreverdelete', 191, 1),
(2, 'Ad', 'Ad', 'preview', 192, 1),
(2, 'Ad', 'Ad', 'make', 193, 1),
(2, 'Filemanager', 'Filemanager', 'index', 197, 1),
(2, 'Filemanager', 'Filemanager', 'adddir', 198, 1),
(2, 'Filemanager', 'Filemanager', 'addfile', 199, 1),
(2, 'Filemanager', 'Filemanager', 'update', 201, 1),
(2, 'Filemanager', 'Filemanager', 'copy', 202, 1),
(2, 'Filemanager', 'Filemanager', 'rname', 203, 1),
(2, 'Filemanager', 'Filemanager', 'move', 205, 1),
(2, 'Filemanager', 'Filemanager', 'foreverdelete', 206, 1),
(2, 'Link', 'Linktype', 'index', 209, 1),
(2, 'Link', 'Linktype', 'add', 210, 1),
(2, 'Link', 'Linktype', 'update', 211, 1),
(2, 'Link', 'Linktype', 'foreverdelete', 212, 1),
(2, 'Link', 'Friendlink', 'index', 215, 1),
(2, 'Link', 'Friendlink', 'add', 216, 1),
(2, 'Link', 'Friendlink', 'update', 217, 1),
(2, 'Link', 'Friendlink', 'foreverdelete', 218, 1),
(2, 'Link', 'Friendlink', 'forbid', 219, 1),
(2, 'Link', 'Friendlink', 'resume', 220, 1);

DROP TABLE IF EXISTS `jiudu_ad`;
CREATE TABLE `jiudu_ad` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `typeid` int(11) NOT NULL,
  `type` tinyint(3) NOT NULL,
  `title` varchar(100) NOT NULL,
  `picurl` varchar(200) NOT NULL,
  `pic_width` smallint(6) NOT NULL,
  `pic_height` smallint(6) NOT NULL,
  `text` varchar(250) NOT NULL,
  `description` varchar(250) NOT NULL,
  `htmlcode` text NOT NULL,
  `alt` varchar(100) NOT NULL,
  `url` varchar(255) NOT NULL,
  `onclick` int(11) NOT NULL,
  `target` varchar(10) NOT NULL,
  `starttime` int(11) NOT NULL,
  `endtime` int(11) NOT NULL,
  `reptext` text NOT NULL,
  `remark` varchar(255) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `typeid` (`typeid`),
  KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_addonarticle`;
CREATE TABLE `jiudu_addonarticle` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_addonimage`;
CREATE TABLE `jiudu_addonimage` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pic_list` text NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_addonsoft`;
CREATE TABLE `jiudu_addonsoft` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `softrank` enum('1','2','3','4','5') NOT NULL,
  `softtype` enum('国产软件','国外软件','汉化补丁') NOT NULL,
  `language` enum('简体中文','英文软件','繁体中文','其它类型') NOT NULL,
  `accredit` enum('共享软件','免费软件','开源软件','商业软件','破解软件') NOT NULL,
  `os` varchar(250) NOT NULL,
  `officialurl` varchar(250) NOT NULL,
  `officialdemo` varchar(250) NOT NULL,
  `softsize` varchar(250) NOT NULL,
  `softurl` text NOT NULL,
  `softurl_local` varchar(200) NOT NULL,
  `softurl_list1` text NOT NULL,
  `softurl_list2` text NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_ad_type`;
CREATE TABLE `jiudu_ad_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

INSERT INTO `jiudu_ad_type` (`id`, `name`) VALUES (1, '默认分类');

DROP TABLE IF EXISTS `jiudu_archives`;
CREATE TABLE `jiudu_archives` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `typeid` int(11) NOT NULL,
  `aid` int(11) NOT NULL DEFAULT '0',
  `cid` int(11) NOT NULL DEFAULT '0',
  `flag` set('c','h','p','f','s','j','a','b') DEFAULT NULL,
  `click` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `title` varchar(100) NOT NULL,
  `shorttitle` varchar(50) NOT NULL,
  `writer` varchar(20) NOT NULL,
  `source` varchar(30) NOT NULL,
  `litpic` varchar(100) NOT NULL,
  `pubdate` int(11) NOT NULL,
  `uid` int(11) NOT NULL,
  `keywords` varchar(100) NOT NULL,
  `description` varchar(255) NOT NULL,
  `weight` int(11) NOT NULL,
  `url` varchar(200) DEFAULT NULL,
  `status` tinyint(1) NOT NULL,
  `sortrank` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `typeid` (`typeid`),
  KEY `uid` (`uid`),
  KEY `status` (`status`),
  KEY `sortrank` (`sortrank`),
  KEY `weight` (`weight`),
  KEY `flag` (`flag`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_arctype`;
CREATE TABLE `jiudu_arctype` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL,
  `cid` int(11) NOT NULL DEFAULT '0',
  `typename` varchar(30) NOT NULL,
  `seotitle` varchar(200) NOT NULL,
  `keywords` varchar(100) NOT NULL,
  `description` varchar(200) NOT NULL,
  `typeimg` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `ispart` tinyint(5) NOT NULL,
  `typedir` varchar(160) NOT NULL,
  `dirname` varchar(100) NOT NULL,
  `referpath` varchar(3) NOT NULL DEFAULT '0',
  `isdefault` tinyint(1) NOT NULL DEFAULT '1',
  `defaultname` varchar(50) NOT NULL DEFAULT 'index',
  `siteurl` varchar(150) NOT NULL,
  `typeurl` varchar(200) NOT NULL,
  `tempindex` varchar(60) NOT NULL,
  `templist` varchar(60) NOT NULL,
  `temparticle` varchar(60) NOT NULL,
  `listrule` varchar(100) NOT NULL,
  `arctrule` varchar(100) NOT NULL,
  `listnum` int(11) NOT NULL DEFAULT '12',
  `linknum` int(11) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `sortrank` smallint(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `pid` (`pid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_comment`;
CREATE TABLE `jiudu_comment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reid` int(11) NOT NULL DEFAULT '0',
  `path` varchar(10) NOT NULL DEFAULT '0',
  `aid` int(11) NOT NULL,
  `tid` int(11) NOT NULL,
  `name` varchar(30) NOT NULL,
  `email` varchar(30) NOT NULL,
  `ip` varchar(30) NOT NULL,
  `time` int(11) NOT NULL,
  `content` varchar(200) NOT NULL,
  `reply` tinyint(1) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_conmodel`;
CREATE TABLE `jiudu_conmodel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `typename` varchar(30) NOT NULL,
  `udid` varchar(30) NOT NULL,
  `addtable` varchar(50) NOT NULL,
  `listfields` varchar(200) NOT NULL,
  `fieldset` text NOT NULL,
  `status` tinyint(1) NOT NULL,
  `notdel` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

INSERT INTO `jiudu_conmodel` (`id`, `typename`, `udid`, `addtable`, `listfields`, `fieldset`, `status`, `notdel`) VALUES
(1, '普通文章', 'article', 'addonarticle', '', '<jiudu:editor itemname="文档内容" name="content" id="content" class="0" value=""></jiudu:editor>\r\n', 1, 1),
(2, '图片集', 'image', 'addonimage', '', '<jiudu:imglists itemname="图片集合" name="pic_list" id="pic_list" class="" type="" value=""></jiudu:imglists>\r\n<jiudu:editor itemname="图集内容" name="content" id="content" class="" type="" value=""></jiudu:editor>\r\n', 1, 1),
(3, '软件', 'soft', 'addonsoft', '', '<jiudu:select itemname="软件等级" name="softrank" id="softrank" class="" type="" value="1,2,3,4,5" msg="选择软件等级"></jiudu:select>\r\n<jiudu:select itemname="软件类型" name="softtype" id="softtype" class="" type="" value="国产软件,国外软件,汉化补丁"></jiudu:select>\r\n<jiudu:select itemname="界面语言" name="language" id="language" class="" type="" value="简体中文,英文软件,繁体中文,其它类型"></jiudu:select>\r\n<jiudu:select itemname="授权方式" name="accredit" id="accredit" class="" type="" value="共享软件,免费软件,开源软件,商业软件,破解软件"></jiudu:select>\r\n<jiudu:input itemname="运行环境" name="os" id="os" class="" type="text" value=""></jiudu:input>\r\n<jiudu:input itemname="官方网址" name="officialurl" id="officialurl" class="" type="text" value="http://"></jiudu:input>\r\n<jiudu:input itemname="演示地址" name="officialdemo" id="officialdemo" class="" type="text" value="http://"></jiudu:input>\r\n<jiudu:input itemname="软件大小" name="softsize" id="softsize" class="" type="text" value="" msg="软件大小，留空系统会自动获取"></jiudu:input>\r\n<jiudu:filelists itemname="软件地址" name="softurl" id="softurl" class="" type="" value=""></jiudu:filelists>\r\n<jiudu:editor itemname="软件详细介绍" name="content" id="content" class="" type="" value="" msg="软件详细介绍"></jiudu:editor>\r\n', 1, 1);

DROP TABLE IF EXISTS `jiudu_diyforms`;
CREATE TABLE `jiudu_diyforms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `table` varchar(50) NOT NULL,
  `verify` tinyint(1) NOT NULL DEFAULT '1' COMMENT '验证码',
  `auditing` tinyint(1) NOT NULL DEFAULT '1' COMMENT '审核',
  `field` varchar(200) NOT NULL,
  `fieldset` text NOT NULL,
  `tempfile` varchar(100) NOT NULL,
  `status` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `table` (`table`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_edition`;
CREATE TABLE `jiudu_edition` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` varchar(50) NOT NULL COMMENT '版本名称',
  `udid` varchar(50) NOT NULL COMMENT '版本标识符',
  `type` varchar(20) NOT NULL COMMENT '版本类型',
  `isdefault` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否默认版本',
  `iscore` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否系统核心',
  `url` varchar(100) NOT NULL COMMENT '域名，目录',
  `create_time` int(11) NOT NULL,
  `update_time` int(11) NOT NULL,
  `status` int(1) NOT NULL COMMENT '状态',
  `remark` varchar(200) NOT NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='版本控制' AUTO_INCREMENT=5 ;

INSERT INTO `jiudu_edition` (`id`, `name`, `udid`, `type`, `isdefault`, `iscore`, `url`, `create_time`, `update_time`, `status`, `remark`) VALUES
(1, '电脑版', 'Web', 'Home', 1, 0, 'http://www.jiuducms.com', 1384764116, 1403515321, 1, '默认电脑版，不可以删除'),
(2, '3G版', 'C', 'Wap', 1, 1, '', 1384764177, 1385102274, 1, ''),
(3, '炫彩版', 'B', 'Wap', 1, 1, '', 1384764177, 1385102274, 1, ''),
(4, '极速版', 'A', 'Wap', 0, 1, '', 1385101776, 1385102449, 1, '');

DROP TABLE IF EXISTS `jiudu_edition_rule`;
CREATE TABLE `jiudu_edition_rule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `eid` int(11) NOT NULL COMMENT '版本ID',
  `tid` int(11) NOT NULL,
  `name` varchar(50) NOT NULL COMMENT '名称',
  `device` text NOT NULL,
  `status` tinyint(1) NOT NULL COMMENT '状态',
  `remark` varchar(200) NOT NULL COMMENT '备注',
  `sortrank` int(11) NOT NULL COMMENT '优先级',
  PRIMARY KEY (`id`),
  KEY `eid` (`eid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='版本规则表' AUTO_INCREMENT=5 ;

INSERT INTO `jiudu_edition_rule` (`id`, `eid`, `tid`, `name`, `device`, `status`, `remark`, `sortrank`) VALUES
(1, 1, 2, '电脑版分流', 'windows 98|windows me|windows 2000|windows xp|windows nt|ubuntu|macintosh|baiduspider|googlebot|ipad', 1, '', 1),
(2, 2, 2, '3G版分流', 'iphone|ipod|android|mi-one|htc|juc|windows phone|m9', 1, '', 2),
(3, 3, 2, '炫彩版分流', 'iuc|ios|htc|samsung|symbianos|e63|nokia5233|nokia86|8mp|opera|ucweb7.6|ucweb7.9', 1, '', 3),
(4, 4, 2, '极速版分流', 'maui wap|nokia5700|nokia5233|nokian72|wap', 0, '', 4);

DROP TABLE IF EXISTS `jiudu_edition_type`;
CREATE TABLE `jiudu_edition_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL,
  `value` varchar(100) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

INSERT INTO `jiudu_edition_type` (`id`, `pid`, `name`, `value`, `status`) VALUES
(1, 0, 'HTTP信息', '', 1),
(2, 1, 'HTTP头信息', 'HTTP_USER_AGENT', 1),
(3, 1, 'HTTP网关', 'HTTP_VIA', 1),
(4, 1, 'HTTP接受类型', 'HTTP_ACCEPT', 1),
(5, 1, 'HTTP特有信息', 'headers', 1);

DROP TABLE IF EXISTS `jiudu_field`;
CREATE TABLE `jiudu_field` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mid` int(11) NOT NULL,
  `itemname` varchar(30) NOT NULL,
  `fieldname` varchar(30) NOT NULL,
  `dtype` int(11) NOT NULL,
  `vdefault` varchar(200) NOT NULL,
  `maxlength` varchar(6) NOT NULL,
  `isnull` tinyint(1) NOT NULL DEFAULT '0',
  `autofield` tinyint(1) NOT NULL DEFAULT '1' COMMENT '自动表单',
  `fieldset` text NOT NULL,
  `msg` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=14 ;

INSERT INTO `jiudu_field` (`id`, `mid`, `itemname`, `fieldname`, `dtype`, `vdefault`, `maxlength`, `isnull`, `autofield`, `fieldset`, `msg`) VALUES
(1, 1, '文档内容', 'content', 4, '', '250', 0, 0, '<field:editor itemname="文档内容" name="content" id="content" class="0" value=""></field:editor>\r\n', ''),
(2, 2, '图片集合', 'pic_list', 8, '', '250', 0, 0, '<field:imglists itemname="图片集合" name="pic_list" id="pic_list" class="" type="" value=""></field:imglists>\r\n', ''),
(3, 2, '图集内容', 'content', 4, '', '250', 0, 0, '<field:editor itemname="图集内容" name="content" id="content" class="" type="" value=""></field:editor>\r\n', ''),
(4, 3, '软件等级', 'softrank', 12, '1,2,3,4,5', '250', 0, 0, '<field:select itemname="软件等级" name="softrank" id="softrank" class="" type="" value="1,2,3,4,5" msg="选择软件等级"></field:select>\r\n', '选择软件等级'),
(5, 3, '软件类型', 'softtype', 12, '国产软件,国外软件,汉化补丁', '250', 0, 0, '<field:select itemname="软件类型" name="softtype" id="softtype" class="" type="" value="国产软件,国外软件,汉化补丁"></field:select>\r\n', ''),
(6, 3, '界面语言', 'language', 12, '简体中文,英文软件,繁体中文,其它类型', '250', 0, 0, '<field:select itemname="界面语言" name="language" id="language" class="" type="" value="简体中文,英文软件,繁体中文,其它类型"></field:select>\r\n', ''),
(7, 3, '授权方式', 'accredit', 12, '共享软件,免费软件,开源软件,商业软件,破解软件', '250', 0, 0, '<field:select itemname="授权方式" name="accredit" id="accredit" class="" type="" value="共享软件,免费软件,开源软件,商业软件,破解软件"></field:select>\r\n', ''),
(8, 3, '运行环境', 'os', 1, '', '250', 0, 0, '<field:input itemname="运行环境" name="os" id="os" class="" type="text" value=""></field:input>\r\n', ''),
(9, 3, '官方网址', 'officialurl', 1, 'http://', '250', 0, 0, '<field:input itemname="官方网址" name="officialurl" id="officialurl" class="" type="text" value="http://"></field:input>\r\n', ''),
(10, 3, '演示地址', 'officialdemo', 1, 'http://', '250', 0, 0, '<field:input itemname="演示地址" name="officialdemo" id="officialdemo" class="" type="text" value="http://"></field:input>\r\n', ''),
(11, 3, '软件大小', 'softsize', 1, '', '250', 0, 0, '<field:input itemname="软件大小" name="softsize" id="softsize" class="" type="text" value="" msg="软件大小，留空系统会自动获取"></field:input>\r\n', '软件大小，留空系统会自动获取'),
(12, 3, '软件地址', 'softurl', 14, '', '250', 0, 0, '<field:filelists itemname="软件地址" name="softurl" id="softurl" class="" type="" value=""></field:filelists>\r\n', ''),
(13, 3, '软件详细介绍', 'content', 4, '', '250', 0, 0, '<field:editor itemname="软件详细介绍" name="content" id="content" class="" type="" value="" msg="软件详细介绍"></field:editor>\r\n', '软件详细介绍');

DROP TABLE IF EXISTS `jiudu_field_type`;
CREATE TABLE `jiudu_field_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL COMMENT '字段名称',
  `field` varchar(50) NOT NULL COMMENT '字段名',
  `field_type` varchar(20) NOT NULL COMMENT '字段类型',
  `label_type` varchar(20) NOT NULL COMMENT '输入框标签',
  `input_type` varchar(10) NOT NULL COMMENT '输入框类型',
  `length` varchar(10) NOT NULL COMMENT '长度',
  `verify` varchar(150) NOT NULL COMMENT '验证规则',
  `msg` varchar(50) NOT NULL COMMENT '提示语',
  `class` varchar(20) NOT NULL COMMENT '附加class',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态',
  `diyform` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 为自定义表单显示 0 为不显示',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=15 ;

INSERT INTO `jiudu_field_type` (`id`, `name`, `field`, `field_type`, `label_type`, `input_type`, `length`, `verify`, `msg`, `class`, `status`, `diyform`) VALUES
(1, '单行文本(varchar)', 'varchar', 'varchar', 'input', 'text', '200', 'a:2:{i:0;s:3:"LTE";i:1;i:250;}', '最大长度不能大于250', '', 1, 1),
(2, '单行文本(char)', 'char', 'char', 'input', 'text', '200', 'a:2:{i:0;s:3:"LTE";i:1;i:250;}', '最大长度不能大于250', '', 1, 0),
(3, '多行文本', 'textarea', 'varchar', 'textarea', '', '400', 'a:2:{i:0;s:3:"LTE";i:1;i:500;}', '最大长度不能大于500', '', 1, 1),
(4, 'HTML文本', 'html', 'text', 'editor', '', '', '', '123', '', 1, 0),
(5, '整数类型', 'digits', 'int', 'input', 'text', '11', 'a:2:{i:0;s:7:"BETWEEN";i:1;a:2:{i:0;i:1;i:1;i:11;}}', '最大长度必须在1到11之间', 'digits', 1, 1),
(6, '小数类型', 'number', 'float', 'input', 'text', '9,2', 'a:2:{i:0;s:5:"REGEX";i:1;s:13:"^[1-9],[0-5]$";}', '最大长度格式必须为[1-9],[0-5]', 'number', 1, 1),
(7, '时间类型', 'datetime', 'datetime', 'date', 'text', '', '', '', '', 1, 1),
(8, '图片集', 'img', 'text', 'imglists', '', '', '', '', '', 1, 0),
(9, '图片(仅网址)', 'imgfile', 'varchar', 'uploadpic', 'text', '', '', '', '', 1, 1),
(10, '附件类型', 'file', 'varchar', 'uploadfile', 'text', '', '', '', '', 1, 1),
(11, '使用select下拉框', 'select', 'enum', 'select', '', '', 'a:2:{i:0;s:5:"REGEX";i:1;s:114:"^(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z]))(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z])|[,])*,(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z]))+$";}', '默认值必须填写，且用英文“,”分开，如“男,女,人妖”', '', 1, 1),
(12, '使用radio选项卡', 'radio', 'enum', 'radio', 'radio', '', 'a:2:{i:0;s:5:"REGEX";i:1;s:114:"^(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z]))(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z])|[,])*,(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z]))+$";}', '默认值用英文“,”分开，如“男,女,人妖”', '', 1, 1),
(13, 'Checkbox多选框', 'checkbox', 'set', 'checkbox', 'checkbox', '', 'a:2:{i:0;s:5:"REGEX";i:1;s:114:"^(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z]))(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z])|[,])*,(([\\x4e00-\\xFA29])|(\\d)|([A-Za-z]))+$";}', '默认值用英文“,”分开，如“男,女,人妖”', '', 1, 1),
(14, '软件地址', 'filelists', 'text', 'filelists', '', '', '', '', '', 0, 0);

DROP TABLE IF EXISTS `jiudu_formfield`;
CREATE TABLE `jiudu_formfield` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fid` int(11) NOT NULL,
  `itemname` varchar(30) NOT NULL,
  `fieldname` varchar(30) NOT NULL,
  `dtype` varchar(20) NOT NULL,
  `vdefault` varchar(200) NOT NULL,
  `maxlength` smallint(6) NOT NULL,
  `isnull` tinyint(1) NOT NULL DEFAULT '0',
  `listfield` tinyint(1) NOT NULL DEFAULT '0',
  `fieldset` text NOT NULL,
  `msg` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=11 ;

INSERT INTO `jiudu_formfield` (`id`, `fid`, `itemname`, `fieldname`, `dtype`, `vdefault`, `maxlength`, `isnull`, `listfield`, `fieldset`, `msg`) VALUES
(1, 1, '单行文本', 'danhang', '1', '', 250, 1, 1, '<jiudu:input itemname="单行文本" name="danhang" id="danhang" class=" required" type="text" value="" msg=""></jiudu:input>\n', ''),
(2, 1, '多行', 'duohang', '3', '', 250, 0, 0, '<jiudu:textarea itemname="多行" name="duohang" id="duohang" class="" type="" value="" msg=""></jiudu:textarea>\n', ''),
(3, 1, '整数', 'zhengshu', '5', '', 11, 1, 1, '<jiudu:input itemname="整数" name="zhengshu" id="zhengshu" class="digits required" type="text" value="" msg=""></jiudu:input>\n', ''),
(4, 1, '小数', 'xiaoshu', '6', '', 9, 0, 0, '<jiudu:input itemname="小数" name="xiaoshu" id="xiaoshu" class="number" type="text" value="" msg=""></jiudu:input>\n', ''),
(5, 1, '时间类型', 'shijian', '7', '', 250, 0, 0, '<jiudu:date itemname="时间类型" name="shijian" id="shijian" class="" type="text" value="" msg=""></jiudu:date>\n', ''),
(6, 1, '图片', 'tupian', '9', '', 250, 0, 0, '<jiudu:uploadpic itemname="图片" name="tupian" id="tupian" class="" type="text" value="" msg=""></jiudu:uploadpic>\n', ''),
(7, 1, '附件', 'fujian', '10', '', 250, 0, 0, '<jiudu:uploadfile itemname="附件" name="fujian" id="fujian" class="" type="text" value="" msg=""></jiudu:uploadfile>\n', ''),
(8, 1, 'select下拉', 'select', '11', '男,女,人妖', 250, 1, 1, '<jiudu:select itemname="select下拉" name="select" id="select" class=" required" type="" value="男,女,人妖" msg=""></jiudu:select>\n', ''),
(9, 1, 'radio', 'radio', '12', '男,女,人妖', 250, 0, 0, '<jiudu:radio itemname="radio" name="radio" id="radio" class="" type="radio" value="男,女,人妖" msg=""></jiudu:radio>\n', ''),
(10, 1, '多选', 'duoxuan', '13', '男,女,人妖', 250, 0, 0, '<jiudu:checkbox itemname="多选" name="duoxuan" id="duoxuan" class="" type="checkbox" value="男,女,人妖" msg=""></jiudu:checkbox>\n', '');

DROP TABLE IF EXISTS `jiudu_friendlink`;
CREATE TABLE `jiudu_friendlink` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `typeid` int(11) NOT NULL DEFAULT '0',
  `type` tinyint(1) NOT NULL DEFAULT '0',
  `webname` varchar(100) NOT NULL,
  `picurl` varchar(100) NOT NULL,
  `pic_width` int(11) NOT NULL,
  `pic_height` int(11) NOT NULL,
  `weburl` varchar(200) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `sortrank` int(11) NOT NULL DEFAULT '0',
  `linksay` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `typeid` (`typeid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_keywords`;
CREATE TABLE `jiudu_keywords` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `url` varchar(100) NOT NULL,
  `rate` smallint(6) NOT NULL,
  `status` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_linktype`;
CREATE TABLE `jiudu_linktype` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9 ;

INSERT INTO `jiudu_linktype` (`id`, `name`) VALUES
(1, '综合网站'),
(2, '娱乐类'),
(3, '教育类'),
(4, '计算机类'),
(5, '电子商务'),
(6, '网上信息'),
(7, '论坛类'),
(8, '其他类型');

DROP TABLE IF EXISTS `jiudu_loginlog`;
CREATE TABLE `jiudu_loginlog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(30) NOT NULL DEFAULT '',
  `logintime` int(11) NOT NULL,
  `loginip` varchar(20) NOT NULL DEFAULT '',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `password` varchar(30) NOT NULL DEFAULT '',
  `info` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_member`;
CREATE TABLE `jiudu_member` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `account` varchar(64) NOT NULL,
  `nickname` varchar(50) NOT NULL,
  `password` char(32) NOT NULL,
  `last_login_time` int(11) unsigned DEFAULT '0',
  `last_login_ip` varchar(40) DEFAULT NULL,
  `login_count` mediumint(8) unsigned DEFAULT '0',
  `verify` varchar(32) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `tel` varchar(20) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `remark` varchar(255) NOT NULL,
  `create_time` int(11) unsigned NOT NULL,
  `update_time` int(11) unsigned NOT NULL,
  `status` tinyint(1) DEFAULT '0',
  `role_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `account` (`account`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_menu`;
CREATE TABLE `jiudu_menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `name` varchar(50) NOT NULL,
  `group` varchar(20) NOT NULL,
  `model` varchar(20) DEFAULT NULL,
  `action` varchar(20) DEFAULT NULL,
  `url` varchar(200) DEFAULT NULL,
  `rel` varchar(20) DEFAULT NULL,
  `target` varchar(20) DEFAULT NULL,
  `type` tinyint(2) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=39 ;

INSERT INTO `jiudu_menu` (`id`, `pid`, `name`, `group`, `model`, `action`, `url`, `rel`, `target`, `type`, `status`) VALUES
(1, 0, '内容管理', 'Content', '', '', '', '', '', 0, 1),
(2, 1, '文章列表', 'Content', 'Archives', 'index', '', 'Archives', 'navTab', 2, 1),
(3, 1, '栏目列表', 'Content', 'Arctype', 'index', '', 'Arctype', 'navTab', 2, 1),
(4, 1, '专题分类', 'Content', 'TopicType', 'index', '', 'TopicType', 'navTab', 2, 1),
(5, 1, '专题列表', 'Content', 'Topic', 'index', '', 'Topic', 'navTab', 2, 1),
(6, 1, '文档关键字', 'Content', 'Keywords', 'index', '', 'Keywords', 'navTab', 2, 1),
(7, 1, '搜索关键词', 'Content', 'Searchkey', 'index', '', 'Searchkey', 'navTab', 2, 1),
(8, 0, '版本管理', 'Edition', '', '', '', '', '', 0, 1),
(9, 8, '模板列表', 'Edition', 'Templets', 'index', '', 'Templets', 'navTab', 2, 1),
(10, 8, '版本列表', 'Edition', 'Edition', 'index', '', 'Edition', 'navTab', 2, 1),
(11, 8, '规则列表', 'Edition', 'EditionRule', 'index', '', 'EditionRule', 'navTab', 2, 1),
(12, 8, '智能分流', 'Edition', 'Zntiao', 'index', '', 'Zntiao', 'navTab', 2, 1),
(13, 0, '模型管理', 'Model', '', '', '', '', '', 0, 1),
(14, 13, '内容模型列表', 'Model', 'Conmodel', 'index', '', 'Conmodel', 'navTab', 2, 1),
(15, 13, '自定义菜单', 'Model', 'Diyforms', 'index', '', 'Diyforms', 'navTab', 2, 1),
(16, 0, '模块管理', 'Module', '', '', '', '', '', 0, 1),
(17, 16, '模块列表', 'Admin', 'Module', 'index', '', 'Module', 'navTab', 2, 0),
(18, 16, '广告管理', 'Ad', '', '', '', '', '', 1, 1),
(19, 18, '广告分类', 'Ad', 'AdType', 'index', '', 'AdType', 'navTab', 2, 1),
(20, 18, '广告列表', 'Ad', 'Ad', 'index', '', 'Ad', 'navTab', 2, 1),
(21, 16, '友情链接', 'Link', '', '', '', '', '', 1, 1),
(22, 21, '链接分类', 'Link', 'Linktype', 'index', '', 'Linktype', 'navTab', 2, 1),
(23, 21, '链接列表', 'Link', 'Friendlink', 'index', '', 'Friendlink', 'navTab', 2, 1),
(24, 0, '系统管理', 'Admin', '', '', '', '', '', 0, 1),
(25, 24, '系统用户', 'Admin', 'User', '', '', '', '', 1, 1),
(26, 25, '用户列表', 'Admin', 'User', 'index', '', 'User', 'navTab', 2, 1),
(27, 25, '用户绩效', 'Admin', 'User', 'tongji', '', 'Usertongji', 'navTab', 2, 1),
(28, 25, '用户组', 'Admin', 'Role', 'index', '', 'Role', 'navTab', 2, 1),
(29, 25, '节点管理', 'Admin', 'Node', 'index', '', 'Node', 'navTab', 2, 1),
(30, 25, '登录记录', 'Admin', 'Loginlog', 'index', '', 'Loginlog', 'navTab', 2, 1),
(31, 25, '操作记录', 'Admin', 'Syslog', 'index', '', 'Syslog', 'navTab', 2, 0),
(32, 24, '系统设置', 'Admin', '', '', '', '', '', 1, 1),
(33, 32, '系统基本设置', 'Admin', 'Sysconfig', 'index', '', 'Sysconfig', 'navTab', 2, 1),
(34, 32, '图片水印设置', 'Admin', 'Sysconfig', 'watermark', '', 'watermark', 'navTab', 2, 1),
(35, 32, '软件频道设置', 'Admin', 'Sysconfig', 'soft', '', 'Sysconfigsoft', 'navTab', 2, 1),
(36, 24, '菜单管理', 'Admin', 'Menu', 'index', '', 'Menu', 'navTab', 2, 1),
(37, 24, '数据更新', 'Admin', 'Makehtml', 'index', '', 'Makehtml', 'navTab', 2, 1),
(38, 24, '数据库管理', 'Admin', 'Sysdata', 'index', '', 'Sysdata', '', 2, 1);

DROP TABLE IF EXISTS `jiudu_module`;
CREATE TABLE `jiudu_module` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `modulename` varchar(100) NOT NULL COMMENT '模块名称',
  `module` varchar(100) NOT NULL COMMENT '模块',
  `version` varchar(10) NOT NULL COMMENT '版本号',
  `author` varchar(30) NOT NULL COMMENT '作者',
  `authorsite` varchar(100) DEFAULT NULL COMMENT '作者网址',
  `authoremail` varchar(100) DEFAULT NULL COMMENT '作者邮箱',
  `description` varchar(250) DEFAULT NULL COMMENT '模块描述',
  `setting` mediumint(9) DEFAULT NULL COMMENT '设置信息',
  `url` varchar(200) DEFAULT NULL,
  `iscore` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否系统核心',
  `installdate` int(11) NOT NULL COMMENT '安装时间',
  `updatedate` int(11) NOT NULL COMMENT '更新时间',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否可用',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;

INSERT INTO `jiudu_module` (`id`, `modulename`, `module`, `version`, `author`, `authorsite`, `authoremail`, `description`, `setting`, `url`, `iscore`, `installdate`, `updatedate`, `status`) VALUES
(1, '后台管理', 'Admin', '1.4.0', 'struggle', 'http://www.jiuducms.com', 'struggle@9ducx.com', '后台管理', NULL, NULL, 1, 1357465373, 1383787092, 1),
(2, '内容模块', 'Content', '1.4.0', 'struggle', 'http://www.jiuducms.com', 'struggle@9ducx.com', '内容管理模块', NULL, NULL, 1, 1383787092, 1383787092, 1),
(3, '模板模块', 'Templets', '1.4.0', 'struggle', 'http://www.jiuducms.com', 'struggle@9ducx.com', '模板管理模块', NULL, NULL, 1, 1383787092, 1383787092, 1),
(4, '模型管理', 'Model', '1.4.0', 'struggle', 'http://www.jiuducms.com', 'struggle@9ducx.com', '模型管理', NULL, NULL, 1, 1383787092, 1383787092, 1),
(5, '广告模块', 'Ad', '1.4.0', 'struggle', 'http://www.jiuducms.com', 'struggle@9ducx.com', '广告模块', NULL, NULL, 1, 1383787092, 1383787092, 1),
(6, '友情链接', 'Link', '1.4.0', 'struggle', 'http://www.jiuducms.com', 'struggle@9ducx.com', '友情链接', NULL, NULL, 1, 1383787092, 1383787092, 1);

DROP TABLE IF EXISTS `jiudu_node`;
CREATE TABLE `jiudu_node` (
  `id` smallint(6) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL,
  `name` varchar(20) NOT NULL,
  `title` varchar(50) NOT NULL,
  `core` tinyint(1) NOT NULL DEFAULT '0',
  `sort` int(11) NOT NULL,
  `level` tinyint(3) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=221 ;

INSERT INTO `jiudu_node` (`id`, `pid`, `name`, `title`, `core`, `sort`, `level`, `status`) VALUES
(1, 0, 'Admin', '系统后台', 1, 0, 1, 1),
(2, 0, 'Content', '内容模块', 1, 0, 1, 1),
(3, 0, 'Edition', '版本管理', 1, 0, 1, 1),
(4, 0, 'Model', '模型管理', 1, 0, 1, 1),
(5, 0, 'Ad', '广告模块', 1, 0, 1, 1),
(6, 0, 'Filemanager', '文件资源管理', 1, 0, 1, 1),
(7, 0, 'Link', '友情链接', 1, 0, 1, 1),
(8, 1, 'Index', '后台首页', 1, 0, 2, 0),
(9, 1, 'User', '系统用户', 1, 0, 2, 1),
(10, 1, 'Role', '系统用户组', 1, 0, 2, 1),
(11, 1, 'Sysconfig', '系统设置', 1, 0, 2, 1),
(12, 1, 'Module', '模块管理', 1, 0, 2, 1),
(13, 1, 'Makehtml', '数据更新', 1, 0, 2, 1),
(14, 1, 'Sysdata', '数据库管理', 1, 0, 2, 1),
(15, 1, 'Node', '节点管理', 1, 0, 2, 1),
(16, 1, 'Menu', '菜单管理', 1, 0, 2, 1),
(17, 1, 'Loginlog', '系统登录日志', 1, 0, 2, 1),
(18, 1, 'Syslog', '系统操作日志', 1, 0, 2, 1),
(19, 2, 'Archives', '文档管理', 1, 0, 2, 1),
(20, 2, 'Arctype', '栏目管理', 1, 0, 2, 1),
(21, 2, 'TopicType', '专题分类', 1, 0, 2, 1),
(22, 2, 'Topic', '专题管理', 1, 0, 2, 1),
(23, 2, 'Keywords', '文档关键字', 1, 0, 2, 1),
(24, 2, 'Searchkey', '搜索关键词', 1, 0, 2, 1),
(25, 3, 'Templets', '模板管理', 1, 0, 2, 1),
(26, 3, 'Edition', '版本列表', 1, 0, 2, 1),
(27, 3, 'EditionRule', '版本规则管理', 1, 0, 2, 1),
(28, 3, 'Zntiao', '智能分流', 1, 0, 2, 1),
(29, 4, 'Conmodel', '内容模型管理', 1, 0, 2, 1),
(30, 4, 'Field', '模型字段管理', 1, 0, 2, 1),
(31, 4, 'Diyforms', '自定义表单', 1, 0, 2, 1),
(32, 4, 'Formfield', '自定义表单字段', 1, 0, 2, 1),
(33, 4, 'Formdata', '自定义表单数据', 1, 0, 2, 1),
(34, 8, 'index', '首页', 1, 0, 3, 1),
(35, 9, 'index', '列表', 1, 0, 3, 1),
(36, 9, 'add', '添加', 1, 0, 3, 1),
(37, 9, 'uodate', '修改', 1, 0, 3, 1),
(38, 9, 'foreverdelete', '删除', 1, 0, 3, 1),
(39, 9, 'password', '修改密码', 1, 0, 3, 1),
(40, 9, 'forbid', '禁用', 1, 0, 3, 1),
(41, 9, 'resume', '启用', 1, 0, 3, 1),
(42, 9, 'tongji', '绩效统计', 1, 0, 3, 1),
(43, 10, 'index', '列表', 1, 0, 3, 1),
(44, 10, 'add', '添加', 1, 0, 3, 1),
(45, 10, 'update', '修改', 1, 0, 3, 1),
(46, 10, 'foreverdelete', '删除', 1, 0, 3, 1),
(47, 10, 'privilege', '编辑权限', 1, 0, 3, 1),
(48, 10, 'forbid', '禁用', 1, 0, 3, 1),
(49, 10, 'resume', '启用', 1, 0, 3, 1),
(50, 11, 'index', '列表', 1, 0, 3, 1),
(51, 11, 'add', '添加', 1, 0, 3, 1),
(52, 11, 'update', '修改', 1, 0, 3, 1),
(53, 11, 'foreverdelete', '删除', 1, 0, 3, 1),
(54, 11, 'watermark', '图片水印设置', 1, 0, 3, 1),
(55, 11, 'soft', '软件频道设置', 1, 0, 3, 1),
(56, 12, 'index', '列表', 1, 0, 3, 1),
(57, 12, 'add', '添加', 1, 0, 3, 1),
(58, 12, 'foreverdelete', '删除', 1, 0, 3, 1),
(59, 12, 'install', '安装', 1, 0, 3, 1),
(60, 12, 'uninstall', '卸载', 1, 0, 3, 1),
(61, 12, 'info', '详细', 1, 0, 3, 1),
(62, 13, 'index', '数据更新', 1, 0, 3, 1),
(63, 13, 'home', '生成首页', 1, 0, 3, 1),
(64, 13, 'arctype', '生成栏目页', 1, 0, 3, 1),
(65, 13, 'archives', '生成内容页', 1, 0, 3, 1),
(66, 13, 'topic', '生成专题页', 1, 0, 3, 1),
(67, 13, 'ad', '更新广告JS文件', 1, 0, 3, 1),
(68, 14, 'index', '列表', 1, 0, 3, 1),
(69, 14, 'backup', '备份', 1, 0, 3, 1),
(70, 14, 'restore', '恢复', 1, 0, 3, 1),
(71, 14, 'repair', '修复', 1, 0, 3, 1),
(72, 14, 'optimize', '优化', 1, 0, 3, 1),
(73, 14, 'structure', '结构', 1, 0, 3, 1),
(74, 14, 'foreverdelete', '删除', 1, 0, 3, 1),
(75, 14, 'truncate', '清空', 1, 0, 3, 1),
(76, 15, 'index', '列表', 1, 0, 3, 1),
(77, 15, 'add', '添加', 1, 0, 3, 1),
(78, 15, 'uodate', '修改', 1, 0, 3, 1),
(79, 15, 'foreverdelete', '删除', 1, 0, 3, 1),
(80, 15, 'forbid', '禁用', 1, 0, 3, 1),
(81, 15, 'resume', '启用', 1, 0, 3, 1),
(82, 16, 'index', '列表', 1, 0, 3, 1),
(83, 16, 'add', '添加', 1, 0, 3, 1),
(84, 16, 'uodate', '修改', 1, 0, 3, 1),
(85, 16, 'foreverdelete', '删除', 1, 0, 3, 1),
(86, 16, 'forbid', '禁用', 1, 0, 3, 1),
(87, 16, 'resume', '启用', 1, 0, 3, 1),
(88, 17, 'index', '列表', 1, 0, 3, 1),
(89, 17, 'foreverdelete', '删除', 1, 0, 3, 1),
(90, 17, 'deleteall', '删除全部', 1, 0, 3, 1),
(91, 17, 'emptydata', '清空', 1, 0, 3, 1),
(92, 18, 'index', '列表', 1, 0, 3, 1),
(93, 18, 'foreverdelete', '删除', 1, 0, 3, 1),
(94, 18, 'deleteall', '删除全部', 1, 0, 3, 1),
(95, 18, 'emptydata', '清空', 1, 0, 3, 1),
(96, 19, 'index', '列表', 1, 0, 3, 1),
(97, 19, 'add', '添加', 1, 0, 3, 1),
(98, 19, 'update', '编辑', 1, 0, 3, 1),
(99, 19, 'foreverdelete', '删除', 1, 0, 3, 1),
(100, 19, 'caozuo', '批量操作', 1, 0, 3, 1),
(101, 19, 'updateflag', '编辑属性', 1, 0, 3, 1),
(102, 19, 'move', '移动', 1, 0, 3, 1),
(103, 19, 'forbid', '禁用', 1, 0, 3, 1),
(104, 19, 'resume', '启用', 1, 0, 3, 1),
(105, 20, 'index', '列表', 1, 0, 3, 1),
(106, 20, 'add', '添加', 1, 0, 3, 1),
(107, 20, 'update', '编辑', 1, 0, 3, 1),
(108, 20, 'foreverdelete', '删除', 1, 0, 3, 1),
(109, 20, 'move', '移动', 1, 0, 3, 1),
(110, 21, 'index', '列表', 1, 0, 3, 1),
(111, 21, 'add', '添加', 1, 0, 3, 1),
(112, 21, 'update', '修改', 1, 0, 3, 1),
(113, 21, 'foreverdelete', '删除', 1, 0, 3, 1),
(114, 22, 'index', '列表', 1, 0, 3, 1),
(115, 22, 'add', '添加', 1, 0, 3, 1),
(116, 22, 'update', '修改', 1, 0, 3, 1),
(117, 22, 'foreverdelete', '删除', 1, 0, 3, 1),
(118, 22, 'forbid', '禁用', 1, 0, 3, 0),
(119, 22, 'resume', '启用', 1, 0, 3, 0),
(120, 23, 'index', '列表', 1, 0, 3, 1),
(121, 23, 'add', '添加', 1, 0, 3, 1),
(122, 23, 'update', '修改', 1, 0, 3, 1),
(123, 23, 'foreverdelete', '删除', 1, 0, 3, 1),
(124, 23, 'forbid', '禁用', 1, 0, 3, 1),
(125, 23, 'resume', '启用', 1, 0, 3, 1),
(126, 24, 'index', '列表', 1, 0, 3, 1),
(127, 24, 'foreverdelete', '删除', 1, 0, 3, 1),
(128, 25, 'index', '列表', 1, 0, 3, 1),
(129, 25, 'add', '新增', 1, 0, 3, 1),
(130, 25, 'update', '修改', 1, 0, 3, 1),
(131, 25, 'foreverdelete', '删除', 1, 0, 3, 1),
(132, 26, 'index', '列表', 1, 0, 3, 1),
(133, 26, 'add', '新增', 1, 0, 3, 1),
(134, 26, 'update', '修改', 1, 0, 3, 1),
(135, 26, 'foreverdelete', '删除', 1, 0, 3, 1),
(136, 26, 'setdefault', '设置默认', 1, 0, 3, 1),
(137, 26, 'forbid', '禁用', 1, 0, 3, 1),
(138, 26, 'resume', '启用', 1, 0, 3, 1),
(139, 27, 'index', '列表', 1, 0, 3, 1),
(140, 27, 'add', '新增', 1, 0, 3, 1),
(141, 27, 'update', '修改', 1, 0, 3, 1),
(142, 27, 'foreverdelete', '删除', 1, 0, 3, 1),
(143, 27, 'sortrank', '更新优先级', 1, 0, 3, 1),
(144, 27, 'forbid', '禁用', 1, 0, 3, 1),
(145, 27, 'resume', '启用', 1, 0, 3, 1),
(146, 28, 'index', '列表', 1, 0, 3, 1),
(147, 28, 'add', '新增', 1, 0, 3, 1),
(148, 28, 'update', '修改', 1, 0, 3, 1),
(149, 28, 'foreverdelete', '删除', 1, 0, 3, 1),
(150, 28, 'forbid', '禁用', 1, 0, 3, 1),
(151, 28, 'resume', '启用', 1, 0, 3, 1),
(152, 29, 'index', '列表', 1, 0, 3, 1),
(153, 29, 'add', '新增', 1, 0, 3, 1),
(154, 29, 'update', '修改', 1, 0, 3, 1),
(155, 29, 'foreverdelete', '删除', 1, 0, 3, 1),
(156, 29, 'forbid', '禁用', 1, 0, 3, 0),
(157, 29, 'resume', '启用', 1, 0, 3, 0),
(158, 30, 'index', '列表', 1, 0, 3, 1),
(159, 30, 'add', '新增', 1, 0, 3, 1),
(160, 30, 'update', '修改', 1, 0, 3, 1),
(161, 30, 'foreverdelete', '删除', 1, 0, 3, 1),
(162, 30, 'forbid', '禁用', 1, 0, 3, 0),
(163, 30, 'resume', '启用', 1, 0, 3, 0),
(164, 31, 'index', '列表', 1, 0, 3, 1),
(165, 31, 'add', '新增', 1, 0, 3, 1),
(166, 31, 'update', '修改', 1, 0, 3, 1),
(167, 31, 'foreverdelete', '删除', 1, 0, 3, 1),
(168, 31, 'forbid', '禁用', 1, 0, 3, 1),
(169, 31, 'resume', '启用', 1, 0, 3, 1),
(170, 32, 'index', '列表', 1, 0, 3, 1),
(171, 32, 'add', '新增', 1, 0, 3, 1),
(172, 32, 'update', '修改', 1, 0, 3, 1),
(173, 32, 'foreverdelete', '删除', 1, 0, 3, 1),
(174, 32, 'forbid', '禁用', 1, 0, 3, 0),
(175, 32, 'resume', '启用', 1, 0, 3, 0),
(176, 33, 'index', '列表', 1, 0, 3, 1),
(177, 33, 'add', '新增', 1, 0, 3, 0),
(178, 33, 'update', '修改', 1, 0, 3, 0),
(179, 33, 'foreverdelete', '删除', 1, 0, 3, 1),
(180, 33, 'forbid', '取消审核', 1, 0, 3, 1),
(181, 33, 'resume', '审核', 1, 0, 3, 1),
(182, 5, 'AdType', '广告分类', 1, 0, 2, 1),
(183, 5, 'Ad', '广告管理', 1, 0, 2, 1),
(184, 182, 'index', '列表', 1, 0, 3, 1),
(185, 182, 'add', '添加', 1, 0, 3, 1),
(186, 182, 'update', '修改', 1, 0, 3, 1),
(187, 182, 'foreverdelete', '删除', 1, 0, 3, 1),
(188, 183, 'index', '列表', 1, 0, 3, 1),
(189, 183, 'add', '添加', 1, 0, 3, 1),
(190, 183, 'update', '修改', 1, 0, 3, 1),
(191, 183, 'foreverdelete', '删除', 1, 0, 3, 1),
(192, 183, 'preview', '预览', 1, 0, 3, 1),
(193, 183, 'make', '生成', 1, 0, 3, 1),
(194, 183, 'forbid', '禁用', 1, 0, 3, 0),
(195, 183, 'resume', '启用', 1, 0, 3, 0),
(196, 6, 'Filemanager', '文件管理', 1, 0, 2, 1),
(197, 196, 'index', '列表', 1, 0, 3, 1),
(198, 196, 'adddir', '新增目录', 1, 0, 3, 1),
(199, 196, 'addfile', '新增文件', 1, 0, 3, 1),
(200, 196, 'upload', '上传文件', 1, 0, 3, 0),
(201, 196, 'update', '编辑文件', 1, 0, 3, 1),
(202, 196, 'copy', '复制', 1, 0, 3, 1),
(203, 196, 'rname', '重命名', 1, 0, 3, 1),
(204, 196, 'preview', '预览', 1, 0, 3, 0),
(205, 196, 'move', '移动', 1, 0, 3, 1),
(206, 196, 'foreverdelete', '删除', 1, 0, 3, 1),
(207, 7, 'Linktype', '链接分类', 1, 0, 2, 1),
(208, 7, 'Friendlink', '链接管理', 1, 0, 2, 1),
(209, 207, 'index', '列表', 1, 0, 3, 1),
(210, 207, 'add', '添加', 1, 0, 3, 1),
(211, 207, 'update', '修改', 1, 0, 3, 1),
(212, 207, 'foreverdelete', '删除', 1, 0, 3, 1),
(213, 207, 'forbid', '禁用', 1, 0, 3, 0),
(214, 207, 'resume', '启用', 1, 0, 3, 0),
(215, 208, 'index', '列表', 1, 0, 3, 1),
(216, 208, 'add', '添加', 1, 0, 3, 1),
(217, 208, 'update', '修改', 1, 0, 3, 1),
(218, 208, 'foreverdelete', '删除', 1, 0, 3, 1),
(219, 208, 'forbid', '禁用', 1, 0, 3, 1),
(220, 208, 'resume', '启用', 1, 0, 3, 1);

DROP TABLE IF EXISTS `jiudu_role`;
CREATE TABLE `jiudu_role` (
  `id` smallint(6) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `ename` varchar(5) DEFAULT NULL,
  `create_time` int(11) unsigned NOT NULL,
  `update_time` int(11) unsigned NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `ename` (`ename`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

INSERT INTO `jiudu_role` (`id`, `name`, `remark`, `ename`, `create_time`, `update_time`, `status`) VALUES
(1, '超级管理员组', '拥有网站最高管理员权限！不能修改，不能删除', '', 1208784792, 1347428301, 1),
(2, '站点管理员组', '', '', 1363000216, 1363000254, 1),
(3, '编辑组', '', '', 1363000233, 0, 1);

DROP TABLE IF EXISTS `jiudu_searchkey`;
CREATE TABLE `jiudu_searchkey` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `keyword` varchar(30) NOT NULL,
  `spwords` varchar(50) NOT NULL,
  `count` int(11) NOT NULL DEFAULT '1',
  `lasttime` int(11) NOT NULL,
  `cid` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `keyword` (`keyword`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_sysconfig`;
CREATE TABLE `jiudu_sysconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `varname` varchar(50) NOT NULL,
  `info` varchar(100) NOT NULL,
  `groupid` smallint(6) NOT NULL,
  `type` varchar(10) NOT NULL,
  `extra` varchar(255) NOT NULL,
  `value` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `varname` (`varname`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=85 ;

INSERT INTO `jiudu_sysconfig` (`id`, `varname`, `info`, `groupid`, `type`, `extra`, `value`) VALUES
(1, 'JIUDU_BASEHOST', '站点根网址', 1, 'string', '', 'http://www.jiuducms.com'),
(2, 'JIUDU_INDEXURL', '主页链接', 1, 'string', '', '/'),
(3, 'JIUDU_INDEXNAME', '主页链接名', 1, 'string', '', '首页'),
(4, 'JIUDU_WEBNAME', '网站名称', 1, 'string', '', '九度网站内容管理系统(JiuduCMS)'),
(6, 'TEMPLETS_PATH', '模板默认路径', 1, 'string', '', 'templets'),
(7, 'TEMPLETS_STYLE', '模板默认风格', 1, 'string', '', 'default'),
(8, 'HTML_FILE_SUFFIX', '静态后缀', 1, 'string', '', '.html'),
(9, 'JIUDU_POWERBY', '网站版权信息', 1, 'bstring', '', 'Copyright © 2011-2015 九度网站内容管理系统 (JiuduCMS)'),
(10, 'JIUDU_KEYWORDS', '站点默认关键字', 1, 'string', '', ''),
(11, 'JIUDU_DESCRIPTION', '站点描述', 1, 'bstring', '', '九度网站内容管理系统(JiuduCMS),是一款完全开源免费的PHP+MYSQL系统.核心采用了Thinkphp框架等众多开源软件,同时核心功能也作为开源软件发布'),
(12, 'JIUDU_BEIAN', '网站备案号', 1, 'string', '', '网站备案号'),
(13, 'JIUDU_FROM_NAME', '网站发信EMAIL', 2, 'string', '', '网站发信'),
(14, 'JIUDU_SENDMAIL_BYSMT', '是否启用smtp方式发送邮件', 2, 'bool', '', '1'),
(15, 'JIUDU_SMTP_SERVER', 'smtp服务器', 2, 'string', '', 'smtp.jiuducms.com'),
(16, 'JIUDU_SMTP_PORT', 'smtp服务器端口', 2, 'string', '', '25'),
(17, 'JIUDU_FROM_MAIL', 'SMTP服务器的用户邮箱', 2, 'string', '', 'admin@jiuducms.com'),
(18, 'JIUDU_SMTP_USER', 'SMTP服务器的用户帐号', 2, 'string', '', 'admin@jiuducms.com'),
(19, 'JIUDU_SMTP_PASSWORD', 'SMTP服务器的用户密码', 2, 'string', '', 'admin'),
(20, 'JIUDU_OFFLINE', '站点关闭', 1, 'bool', '', '0'),
(21, 'JIUDU_OFFLINEMESSAGE', '网站关闭，提示信息', 1, 'bstring', '', '本站正在维护中，暂不能访问。<br /> 请稍后再访问本站。'),
(26, 'UPLOAD_PATH', '附件目录', 3, 'string', '', 'Uploads'),
(37, 'UPLOAD_IMG_SIZE', '设置图片上传大小(MB)', 3, 'string', '', '2'),
(38, 'UPLOAD_FILE_SIZE', '设置附件上传大小(MB)', 3, 'string', '', '5'),
(39, 'UPLOAD_IMG_EXTS', '设置图片上传类型(以英文“,”隔开)', 3, 'string', '', 'jpg,gif,png,jpeg'),
(40, 'UPLOAD_FILE_EXTS', '设置附件上传类型(以英文“,”隔开)', 3, 'string', '', 'zip,rar,txt,doc,docx'),
(41, 'JIUDU_TOPPICDIR', '专题存放目录', 2, 'string', '', '/s'),
(42, 'JIUDU_DEFAULT_GRAVAT', '默认评论头像', 2, 'string', '', 'Uploads/gravat.jpg'),
(43, 'JIUDU_DABA_BAK', '数据库备份目录', 2, 'string', '', 'backupData'),
(44, 'JIUDU_SEARCH', '搜索页每页数量', 5, 'string', '', '15'),
(45, 'ARCHIVES_WRITER', '文档作者', 6, 'string', '', 'admin1,admin2,admin3'),
(46, 'ARCHIVES_SOURCE', '文档来源', 6, 'string', '', '北京,南京'),
(47, 'JIUDU_CMSPATH', '程序安装目录', 2, 'string', '', ''),
(50, 'JIUDU_STATISTICS', '统计代码', 1, 'bstring', '', ''),
(51, 'JIUDU_WATERMARK', '是否开启图片水印', 10, 'bool', '', '1'),
(52, 'JIUDU_WATERMARK_D', '水印的文件类型', 10, 'bool', '', '1'),
(53, 'JIUDU_WATERMARK_W', '水印的图片宽', 10, 'string', '', '300'),
(54, 'JIUDU_WATERMARK_H', '水印的图片高', 10, 'string', '', '200'),
(55, 'JIUDU_WATERMARK_U', '水印图片路径', 10, 'string', '', '/Uploads/watermark/mark.png'),
(56, 'JIUDU_WATERMARK_T', '水印透明度', 10, 'string', '', '90'),
(57, 'JIUDU_WATERMARK_Z', 'JPEG 水印质量', 10, 'string', '', '100'),
(58, 'JIUDU_WATERMARK_L', '水印位置', 10, 'string', '', '9'),
(59, 'JIUDU_REPLY_NAME', '回复名称', 2, 'string', '', ''),
(60, 'JIUDU_REPLY_MAIL', '回复EMAIL', 2, 'string', '', ''),
(61, 'JIUDU_CONKEY', '是否开启文章内链', 5, 'bool', '', '1'),
(62, 'JIUDU_MAKE_INDEX', '发布文章后马上更新网站首页', 5, 'bool', '', '0'),
(63, 'JIUDU_MAKE_ANDCAT', '发表文章后马上更新相关栏目', 5, 'bool', '', '1'),
(64, 'JIUDU_MAKE_PRENEXT', '发表文章后马上更新上下篇', 5, 'bool', '', '1'),
(65, 'JIUDU_SYSLOG', '是否开启网站日志', 5, 'bool', '', '1'),
(66, 'JIUDU_LOGINLOG', '是否开启登录日志', 5, 'bool', '', '1'),
(67, 'JIUDU_MENU_CACHE', '是否开启菜单缓存', 5, 'bool', '', '1'),
(68, 'JIUDU_EDITION_SWITCH', '版本控制', 20, 'bool', '', '1'),
(69, 'JIUDU_ZNTIAO_SWITCH', '智能分流', 20, 'bool', '', '0'),
(70, 'JIUDU_WAP_BASEHOST', '手机端独立域名', 20, 'string', '', ''),
(72, 'JIUDU_DIYCODEPOSITIO', '自定义跳转代码位置', 20, 'bool', '', '0'),
(73, 'JIUDU_LINKINFO_ROW', '相关文章标题字数', 5, 'string', '0', '20'),
(74, 'JIUDU_DOWN_SHOWTYPE', '链接显示方式', 8, 'enum', 'a:2:{i:0;s:24:"直接显示地址列表";i:1;s:33:"要求进入下载地址列表页";}', '0'),
(75, 'JIUDU_DOWN_GOTOJUMP', '附件下载方式', 8, 'enum', 'a:2:{i:0;s:27:"链接到真实软件地址";i:1;s:21:"链接到跳转页面";}', '1'),
(76, 'JIUDU_DOWN_ISMORESITE', '是否启用镜像站点', 8, 'enum', 'a:2:{i:1;s:6:"启用";i:0;s:9:"不启用";}', '0'),
(77, 'JIUDU_DOWN_ISLOCAL', '启用镜像站点后是否保留本地下载', 8, 'enum', 'a:2:{i:1;s:6:"保留";i:0;s:9:"不保留";}', '0'),
(78, 'JIUDU_DOWN_MORESITEDO', '镜像处理方式', 8, 'enum', 'a:2:{i:0;s:48:"根据本地地址和服务器列表自动生成";i:1;s:51:"发布时按服务器生成列表由我手工填写";}', '0'),
(79, 'JIUDU_DOWN_SITES', '镜像服务器网址', 8, 'bstring', '', 'http://www.aaa.com|镜像一\r\nhttp://www.bbb.com|镜像二\r\nhttp://www.ccc.com|镜像三'),
(80, 'JIUDU_PAGE_STYLE', '分页样式', 6, 'bstring', '', '<span>%totalRow% 条记录 %nowPage%/%totalPage% 页</span> %upPage% %linkPage% %downPage% %first% %end% '),
(81, 'MB_UPLOAD_IMG_SIZE', '设置前台图片上传大小(MB)', 3, 'string', '', '2'),
(82, 'MB_UPLOAD_FILE_SIZE', '设置前台附件上传大小(MB)', 3, 'string', '', '3'),
(83, 'MB_UPLOAD_IMG_EXTS', '设置前台图片上传类型(以英文","隔开)', 3, 'string', '', 'jpg,gif,png,jpeg'),
(84, 'MB_UPLOAD_FILE_EXTS', '设置前台附件上传类型(以英文","隔开)', 3, 'string', '', 'zip,rar,txt,doc,docx');

DROP TABLE IF EXISTS `jiudu_sysconfig_type`;
CREATE TABLE `jiudu_sysconfig_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=21 ;

INSERT INTO `jiudu_sysconfig_type` (`id`, `name`, `status`) VALUES
(1, '站点设置', 1),
(2, '核心设置', 1),
(3, '附件设置', 1),
(4, '互动设置', 0),
(5, '性能选项', 1),
(6, '其它选项', 1),
(7, '模块设置', 1),
(8, '软件模型设置', 0),
(10, '水印设置', 0),
(20, '版本设置', 1);

DROP TABLE IF EXISTS `jiudu_syslog`;
CREATE TABLE `jiudu_syslog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `appname` varchar(20) DEFAULT NULL,
  `modulename` varchar(20) DEFAULT NULL,
  `actionname` varchar(20) DEFAULT NULL,
  `message` varchar(100) DEFAULT NULL,
  `username` varchar(30) NOT NULL,
  `userid` int(11) NOT NULL,
  `userip` varchar(20) NOT NULL,
  `time` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_templets`;
CREATE TABLE `jiudu_templets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tempname` varchar(100) NOT NULL,
  `tempinfo` varchar(250) NOT NULL,
  `default` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9 ;

INSERT INTO `jiudu_templets` (`id`, `tempname`, `tempinfo`, `default`) VALUES
(1, 'index.html', '首页模板', 1),
(2, 'article_article.html', '内容页模版', 1),
(3, 'list_article.html', '列表页模版', 1),
(4, 'index_article.html', '频道页模版', 1),
(5, 'search.html', '搜索模板', 1),
(6, 'head.html', '公共头部', 1),
(7, 'foot.html', '公共底部', 1),
(8, 'topic_default.html', '默认专题模板', 1);

DROP TABLE IF EXISTS `jiudu_topic`;
CREATE TABLE `jiudu_topic` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `typeid` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `ztpic` varchar(200) NOT NULL,
  `dirname` varchar(150) NOT NULL,
  `typedir` varchar(200) NOT NULL,
  `zturl` varchar(100) NOT NULL,
  `isdefault` tinyint(1) NOT NULL DEFAULT '1',
  `keywords` varchar(150) NOT NULL,
  `description` varchar(255) NOT NULL,
  `sort` int(11) NOT NULL DEFAULT '0',
  `click` int(11) NOT NULL,
  `tempindex` varchar(100) NOT NULL,
  `remark` varchar(255) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `typeid` (`typeid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_topic_type`;
CREATE TABLE `jiudu_topic_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

INSERT INTO `jiudu_topic_type` (`id`, `name`) VALUES
(1, '默认分类');

DROP TABLE IF EXISTS `jiudu_user`;
CREATE TABLE `jiudu_user` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `account` varchar(64) NOT NULL,
  `nickname` varchar(50) NOT NULL,
  `password` char(32) NOT NULL,
  `last_login_time` int(11) unsigned DEFAULT '0',
  `last_login_ip` varchar(40) DEFAULT NULL,
  `login_count` mediumint(8) unsigned DEFAULT '0',
  `verify` varchar(32) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `remark` varchar(255) NOT NULL,
  `create_time` int(11) unsigned NOT NULL,
  `update_time` int(11) unsigned NOT NULL,
  `status` tinyint(1) DEFAULT '0',
  `role_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `account` (`account`),
  UNIQUE KEY `email` (`email`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `jiudu_zntiao`;
CREATE TABLE `jiudu_zntiao` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL COMMENT '标题',
  `pcurl` varchar(150) NOT NULL COMMENT 'PC链接',
  `phoneurl` varchar(150) NOT NULL COMMENT '手机端链接',
  `create_time` int(11) NOT NULL,
  `update_time` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pcurl` (`pcurl`),
  UNIQUE KEY `phoneurl` (`phoneurl`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;